### ISSUE TITLE
 Implementation details of rec = A.T(y_filtered)

### ISSUE THREAD

**Issue by PeterPaang4** [ahendriksen/ts_algorithms#8]
Dear author, hello. I hope I haven’t disturbed you. In the fbp.py file, there is the following code. Can I ask you which code contains the specific implementation details of this line of code?

# Backproject the filtered sinogram to obtain a reconstruction

rec = A.T(y_filtered)

**Comment by D1rk123** [comment]
The backprojection operator is handled by the astra toolbox and the implementation is written in Cuda.

This function calls the \_\_call\_\_ function of the tomosipo BackprojectionOperator, which calls the _bp function of the tomosipo Operator class, which (with some more jumps) calls the direct_FPBP3D function in the python bindings of the Astra toolbox. The backprojection is coded in cuda as part of the Astra toolbox in the cone_bp file.

- BackprojectionOperator.\_\_call\_\_ : https://github.com/ahendriksen/tomosipo/blob/6aa366e4db0550ef19eb46217fa59866e85111d8/tomosipo/Operator.py#L322
- Operator._bp : https://github.com/ahendriksen/tomosipo/blob/6aa366e4db0550ef19eb46217fa59866e85111d8/tomosipo/Operator.py#L194
- astra direct_FPBP3D : https://github.com/astra-toolbox/astra-toolbox/blob/acbb899c4888c35d80c590f6f2ce8429e34f16b5/python/astra/experimental.pyx#L135
- astra cone_bp file : https://github.com/astra-toolbox/astra-toolbox/blob/acbb899c4888c35d80c590f6f2ce8429e34f16b5/cuda/3d/cone_bp.cu

If you have further questions, please do your own research first and be more precise in what you want to know. If you have specific questions about the implementation of the backprojection, I don't think I can answer them, but you could try asking them at the Astra toolbox git repository.

**Comment by PeterPaang4** [comment]
Thank you for your reply, I have solved the problem
